# Select the backend to use. Set to "DEFAULT" or "INSTANCING" for Flywheel GPU Instancing.
backend = "INSTANCING"
# Enable or disable instance update limiting with distance.
limitUpdates = true
# The number of worker threads to use. Set to -1 to let Flywheel decide.
workerThreads = -1

[flw_backends]
	lightSmoothness = "FLAT"
