allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=4
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit) + Clrwl_1.0.5.zip
